# Cloud Build steps
steps:
# Build the container image for deployment
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'dockerfiles/gramai_app.dockerfile', '.', '-t', 'gcr.io/durable-stack-410709/gramai_app:latest']
  id: 'Build the container image for deployment'
  waitFor: ["-"]

# Push the container image for deployment to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/durable-stack-410709/gramai_app:latest']
  id: 'Push the container image for deployment to Container Registry'
  waitFor: ["Build the container image for deployment"]

# Build the container image for training
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'dockerfiles/train_model.dockerfile', '.', '-t', 'gcr.io/durable-stack-410709/train:latest'] 
  id: 'Build the container image for training'
  waitFor: ["-"]

# Push the container image for training to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/durable-stack-410709/train:latest']
  id: 'Push the container image for training to Container Registry'
  waitFor: ["Build the container image for training"]

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'services'
  - 'replace'
  - 'gramai_app_service.yaml'
  - '--region'
  - 'europe-west1'
  id: 'Deploy container image to Cloud Run'
  waitFor: ["Push the container image for deployment to Container Registry"]

options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: '200'
